export const API_ROUTES = {
  health: '/health',

  auth: {
    base: '/auth',
    login: '/auth/login',
    me: '/auth/me',
  },

  chat: {
    base: '/chat',
    voice: '/chat/voice',
    speak: '/chat/speak',
    history: '/chat/history',
    widgetConfig: '/chat/widget-config',
    signup: '/chat/auth/signup',
    login: '/chat/auth/login',
    me: '/chat/auth/me',
  },

  admin: {
    documents: {
      base: '/admin/documents',
      tags: '/admin/documents/tags',
      url: '/admin/documents/url',
      sitemap: '/admin/documents/sitemap',
      text: '/admin/documents/text',
      file: '/admin/documents/file',
      byId: (id: string) => `/admin/documents/${id}`,
      chunks: (id: string) => `/admin/documents/${id}/chunks`,
      export: (id: string) => `/admin/documents/${id}/export`,
      recheck: (id: string) => `/admin/documents/${id}/recheck`,
      pause: (id: string) => `/admin/documents/${id}/pause`,
      setTags: (id: string) => `/admin/documents/${id}/tags`,
    },
    faqs: {
      base: '/admin/faqs',
      byId: (id: string) => `/admin/faqs/${id}`,
      importSeed: '/admin/faqs/import-seed',
      import: '/admin/faqs/import',
    },
    settings: {
      base: '/admin/settings',
      llm: '/admin/settings/llm',
      prompt: '/admin/settings/prompt',
      widget: '/admin/settings/widget',
      widgetIcon: '/admin/settings/widget/icon',
      businessHours: '/admin/settings/business-hours',
      firebase: '/admin/settings/firebase',
      firebaseTestConnection: '/admin/settings/firebase/test-connection',
      cache: '/admin/settings/cache',
      limits: '/admin/settings/limits',
      apiKeys: '/admin/settings/api-keys',
      chunking: '/admin/settings/chunking',
      voice: '/admin/settings/voice',
      speechApiKeys: '/admin/settings/speech-api-keys',
      embeddingApiKeys: '/admin/settings/embedding-api-keys',
      voiceTestSpeech: '/admin/settings/voice/test-speech',
      embeddingTest: '/admin/settings/embeddings/test',
      testLlmKey: '/admin/settings/test-llm-key',
      testSpeechKey: '/admin/settings/test-speech-key',
      cacheFlush: '/admin/settings/cache/flush',
      dbStatus: '/admin/settings/db/status',
      dbMigrate: '/admin/settings/db/migrate',
    },
    stats: '/admin/stats',
    wordUsage: '/admin/stats/word-usage',
    voiceUsage: '/admin/stats/voice-usage',
    conversations: {
      base: '/admin/conversations',
      active: '/admin/conversations/active',
      export: '/admin/conversations/export',
      byId: (id: string) => `/admin/conversations/${id}`,
      blocked: (id: string) => `/admin/conversations/${id}/blocked`,
      compact: (id: string) => `/admin/conversations/${id}/compact`,
    },
    users: {
      base: '/admin/users',
      byId: (id: string) => `/admin/users/${id}`,
      password: (id: string) => `/admin/users/${id}/password`,
      role: (id: string) => `/admin/users/${id}/role`,
    },
    roles: {
      base: '/admin/roles',
      catalog: '/admin/roles/catalog',
      byId: (id: string) => `/admin/roles/${id}`,
    },
    audit: '/admin/audit',
    visitorUsers: {
      base: '/admin/visitor-users',
      byId: (id: string) => `/admin/visitor-users/${id}`,
      password: (id: string) => `/admin/visitor-users/${id}/password`,
      resetQuota: (id: string) => `/admin/visitor-users/${id}/reset-quota`,
    },
    query: '/admin/query',
    unansweredQuestions: {
      base: '/admin/unanswered-questions',
      byId: (id: string) => `/admin/unanswered-questions/${id}`,
      stats: '/admin/unanswered-questions/stats',
    },
    questionChunks: {
      base: '/admin/question-chunks',
      byId: (id: string) => `/admin/question-chunks/${id}`,
    },
    restrictedWords: {
      base: '/admin/restricted-words',
      byId: (id: string) => `/admin/restricted-words/${id}`,
    },
    reports: {
      base: '/admin/reports',
      firebaseStats: '/admin/reports/firebase/stats',
      firebaseCacheStats: '/admin/reports/firebase/cache-stats',
      firebaseConversations: '/admin/reports/firebase/conversations',
      firebaseAnswerSources: '/admin/reports/firebase/answer-sources',
      firebaseConversationMessages: (id: string) => `/admin/reports/firebase/conversations/${id}/messages`,
    },
  },
} as const;
